// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.example.grpc.smartoffices.heating;

public interface HeatingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.HeatingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();

  /**
   * <code>double humidity = 2;</code>
   */
  double getHumidity();

  /**
   * <pre>
   * PM2.5 level
   * </pre>
   *
   * <code>double airPollution = 3;</code>
   */
  double getAirPollution();
}
