// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.example.grpc.smartoffices.heating;

public interface HeatingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.HeatingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * True if heating is on, False if off
   * </pre>
   *
   * <code>bool heatingStatus = 1;</code>
   */
  boolean getHeatingStatus();
}
