// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.example.grpc.smartoffices.heating;

public final class SmartHeatingServiceImpl {
  private SmartHeatingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_HeatingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_HeatingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_HeatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_HeatingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SmartHeating.proto\022\014SmartOffices\"M\n\016He" +
      "atingRequest\022\023\n\013temperature\030\001 \001(\001\022\020\n\010hum" +
      "idity\030\002 \001(\001\022\024\n\014airPollution\030\003 \001(\001\"(\n\017Hea" +
      "tingResponse\022\025\n\rheatingStatus\030\001 \001(\0102\262\001\n\014" +
      "SmartHeating\022M\n\016UpdateSettings\022\034.SmartOf" +
      "fices.HeatingRequest\032\035.SmartOffices.Heat" +
      "ingResponse\022S\n\022MonitorTemperature\022\034.Smar" +
      "tOffices.HeatingRequest\032\035.SmartOffices.H" +
      "eatingResponse0\001BB\n%com.example.grpc.sma" +
      "rtoffices.heatingB\027SmartHeatingServiceIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOffices_HeatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOffices_HeatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_HeatingRequest_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "AirPollution", });
    internal_static_SmartOffices_HeatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOffices_HeatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_HeatingResponse_descriptor,
        new java.lang.String[] { "HeatingStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
