// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.example.grpc.smartoffices.heating;

public final class SmartHeatingServiceImpl {
  private SmartHeatingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TemperatureSettingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TemperatureSettingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SmartHeating.proto\022\014SmartOffices\")\n\031Te" +
      "mperatureSettingRequest\022\014\n\004area\030\001 \001(\t\"&\n" +
      "\023TemperatureResponse\022\017\n\007message\030\001 \001(\t2\360\003" +
      "\n\014SmartHeating\022b\n\022MonitorTemperature\022\'.S" +
      "martOffices.TemperatureSettingRequest\032!." +
      "SmartOffices.TemperatureResponse(\001\022`\n\022Se" +
      "tTemperatureHigh\022\'.SmartOffices.Temperat" +
      "ureSettingRequest\032!.SmartOffices.Tempera" +
      "tureResponse\022_\n\021SetTemperatureLow\022\'.Smar" +
      "tOffices.TemperatureSettingRequest\032!.Sma" +
      "rtOffices.TemperatureResponse\022[\n\rTurnHea" +
      "tingOn\022\'.SmartOffices.TemperatureSetting" +
      "Request\032!.SmartOffices.TemperatureRespon" +
      "se\022\\\n\016TurnHeatingOff\022\'.SmartOffices.Temp" +
      "eratureSettingRequest\032!.SmartOffices.Tem" +
      "peratureResponseBB\n%com.example.grpc.sma" +
      "rtoffices.heatingB\027SmartHeatingServiceIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOffices_TemperatureSettingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOffices_TemperatureSettingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TemperatureSettingRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOffices_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TemperatureResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
