// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.example.grpc.smartoffices.heating;

public final class SmartHeatingServiceImpl {
  private SmartHeatingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_HeatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_HeatingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_HeatingUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_HeatingUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SmartHeating.proto\022\014SmartOffices\"7\n\022Te" +
      "mperatureRequest\022\014\n\004area\030\001 \001(\t\022\023\n\013temper" +
      "ature\030\002 \001(\001\"/\n\017HeatingResponse\022\014\n\004area\030\001" +
      " \001(\t\022\016\n\006status\030\002 \001(\t\"-\n\rHeatingUpdate\022\014\n" +
      "\004area\030\001 \001(\t\022\016\n\006status\030\002 \001(\t2\300\001\n\014SmartHea" +
      "ting\022W\n\022MonitorTemperature\022 .SmartOffice" +
      "s.TemperatureRequest\032\035.SmartOffices.Heat" +
      "ingResponse(\001\022W\n\024StreamHeatingUpdates\022 ." +
      "SmartOffices.TemperatureRequest\032\033.SmartO" +
      "ffices.HeatingUpdate0\001BB\n%com.example.gr" +
      "pc.smartoffices.heatingB\027SmartHeatingSer" +
      "viceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOffices_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOffices_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TemperatureRequest_descriptor,
        new java.lang.String[] { "Area", "Temperature", });
    internal_static_SmartOffices_HeatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOffices_HeatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_HeatingResponse_descriptor,
        new java.lang.String[] { "Area", "Status", });
    internal_static_SmartOffices_HeatingUpdate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartOffices_HeatingUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_HeatingUpdate_descriptor,
        new java.lang.String[] { "Area", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
