// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.example.grpc.smartoffices.heating;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Status message such as "Heating turned on" or "Set temperature to high"
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Status message such as "Heating turned on" or "Set temperature to high"
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
