// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.example.grpc.smartoffices.heating;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifier for the area
   * </pre>
   *
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <pre>
   * Identifier for the area
   * </pre>
   *
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <pre>
   * Current temperature in Celsius
   * </pre>
   *
   * <code>double temperature = 2;</code>
   */
  double getTemperature();
}
