// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLights.proto

package com.example.grpc.smartoffices.light;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();
}
