// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLights.proto

package com.example.grpc.smartoffices.light;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Result message (e.g., "Lights turned on", "Lights turned off")
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Result message (e.g., "Lights turned on", "Lights turned off")
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
