// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLights.proto

package com.example.grpc.smartoffices.light;

public interface OccupancyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.OccupancyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifier for the area (e.g., office 1, office 2, meeting room)
   * </pre>
   *
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <pre>
   * Identifier for the area (e.g., office 1, office 2, meeting room)
   * </pre>
   *
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <pre>
   * Occupancy status: true if occupied, false otherwise.
   * </pre>
   *
   * <code>bool isOccupied = 2;</code>
   */
  boolean getIsOccupied();
}
