// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLights.proto

package com.example.grpc.smartoffices.light;

/**
 * <pre>
 * Request message containing the area and occupancy status.
 * </pre>
 *
 * Protobuf type {@code SmartOffices.OccupancyRequest}
 */
public  final class OccupancyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SmartOffices.OccupancyRequest)
    OccupancyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OccupancyRequest.newBuilder() to construct.
  private OccupancyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OccupancyRequest() {
    area_ = "";
    isOccupied_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OccupancyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            area_ = s;
            break;
          }
          case 16: {

            isOccupied_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.smartoffices.light.SmartLightServiceImpl.internal_static_SmartOffices_OccupancyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.smartoffices.light.SmartLightServiceImpl.internal_static_SmartOffices_OccupancyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.smartoffices.light.OccupancyRequest.class, com.example.grpc.smartoffices.light.OccupancyRequest.Builder.class);
  }

  public static final int AREA_FIELD_NUMBER = 1;
  private volatile java.lang.Object area_;
  /**
   * <pre>
   * Identifier for the area (e.g., office 1, office 2, meeting room)
   * </pre>
   *
   * <code>string area = 1;</code>
   */
  public java.lang.String getArea() {
    java.lang.Object ref = area_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      area_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Identifier for the area (e.g., office 1, office 2, meeting room)
   * </pre>
   *
   * <code>string area = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAreaBytes() {
    java.lang.Object ref = area_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      area_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISOCCUPIED_FIELD_NUMBER = 2;
  private boolean isOccupied_;
  /**
   * <pre>
   * Occupancy status: true if occupied, false otherwise.
   * </pre>
   *
   * <code>bool isOccupied = 2;</code>
   */
  public boolean getIsOccupied() {
    return isOccupied_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAreaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, area_);
    }
    if (isOccupied_ != false) {
      output.writeBool(2, isOccupied_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAreaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, area_);
    }
    if (isOccupied_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isOccupied_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.smartoffices.light.OccupancyRequest)) {
      return super.equals(obj);
    }
    com.example.grpc.smartoffices.light.OccupancyRequest other = (com.example.grpc.smartoffices.light.OccupancyRequest) obj;

    boolean result = true;
    result = result && getArea()
        .equals(other.getArea());
    result = result && (getIsOccupied()
        == other.getIsOccupied());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AREA_FIELD_NUMBER;
    hash = (53 * hash) + getArea().hashCode();
    hash = (37 * hash) + ISOCCUPIED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOccupied());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.smartoffices.light.OccupancyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.smartoffices.light.OccupancyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message containing the area and occupancy status.
   * </pre>
   *
   * Protobuf type {@code SmartOffices.OccupancyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SmartOffices.OccupancyRequest)
      com.example.grpc.smartoffices.light.OccupancyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.smartoffices.light.SmartLightServiceImpl.internal_static_SmartOffices_OccupancyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.smartoffices.light.SmartLightServiceImpl.internal_static_SmartOffices_OccupancyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.smartoffices.light.OccupancyRequest.class, com.example.grpc.smartoffices.light.OccupancyRequest.Builder.class);
    }

    // Construct using com.example.grpc.smartoffices.light.OccupancyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      area_ = "";

      isOccupied_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.smartoffices.light.SmartLightServiceImpl.internal_static_SmartOffices_OccupancyRequest_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.smartoffices.light.OccupancyRequest getDefaultInstanceForType() {
      return com.example.grpc.smartoffices.light.OccupancyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.smartoffices.light.OccupancyRequest build() {
      com.example.grpc.smartoffices.light.OccupancyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.smartoffices.light.OccupancyRequest buildPartial() {
      com.example.grpc.smartoffices.light.OccupancyRequest result = new com.example.grpc.smartoffices.light.OccupancyRequest(this);
      result.area_ = area_;
      result.isOccupied_ = isOccupied_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.smartoffices.light.OccupancyRequest) {
        return mergeFrom((com.example.grpc.smartoffices.light.OccupancyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.smartoffices.light.OccupancyRequest other) {
      if (other == com.example.grpc.smartoffices.light.OccupancyRequest.getDefaultInstance()) return this;
      if (!other.getArea().isEmpty()) {
        area_ = other.area_;
        onChanged();
      }
      if (other.getIsOccupied() != false) {
        setIsOccupied(other.getIsOccupied());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.smartoffices.light.OccupancyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.smartoffices.light.OccupancyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object area_ = "";
    /**
     * <pre>
     * Identifier for the area (e.g., office 1, office 2, meeting room)
     * </pre>
     *
     * <code>string area = 1;</code>
     */
    public java.lang.String getArea() {
      java.lang.Object ref = area_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        area_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Identifier for the area (e.g., office 1, office 2, meeting room)
     * </pre>
     *
     * <code>string area = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAreaBytes() {
      java.lang.Object ref = area_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        area_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Identifier for the area (e.g., office 1, office 2, meeting room)
     * </pre>
     *
     * <code>string area = 1;</code>
     */
    public Builder setArea(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      area_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifier for the area (e.g., office 1, office 2, meeting room)
     * </pre>
     *
     * <code>string area = 1;</code>
     */
    public Builder clearArea() {
      
      area_ = getDefaultInstance().getArea();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Identifier for the area (e.g., office 1, office 2, meeting room)
     * </pre>
     *
     * <code>string area = 1;</code>
     */
    public Builder setAreaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      area_ = value;
      onChanged();
      return this;
    }

    private boolean isOccupied_ ;
    /**
     * <pre>
     * Occupancy status: true if occupied, false otherwise.
     * </pre>
     *
     * <code>bool isOccupied = 2;</code>
     */
    public boolean getIsOccupied() {
      return isOccupied_;
    }
    /**
     * <pre>
     * Occupancy status: true if occupied, false otherwise.
     * </pre>
     *
     * <code>bool isOccupied = 2;</code>
     */
    public Builder setIsOccupied(boolean value) {
      
      isOccupied_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Occupancy status: true if occupied, false otherwise.
     * </pre>
     *
     * <code>bool isOccupied = 2;</code>
     */
    public Builder clearIsOccupied() {
      
      isOccupied_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SmartOffices.OccupancyRequest)
  }

  // @@protoc_insertion_point(class_scope:SmartOffices.OccupancyRequest)
  private static final com.example.grpc.smartoffices.light.OccupancyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.smartoffices.light.OccupancyRequest();
  }

  public static com.example.grpc.smartoffices.light.OccupancyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OccupancyRequest>
      PARSER = new com.google.protobuf.AbstractParser<OccupancyRequest>() {
    @java.lang.Override
    public OccupancyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OccupancyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OccupancyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OccupancyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.smartoffices.light.OccupancyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

