// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLights.proto

package com.example.grpc.smartoffices.light;

public final class SmartLightServiceImpl {
  private SmartLightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_OccupancyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_OccupancyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_LightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SmartLights.proto\022\014SmartOffices\"4\n\020Occ" +
      "upancyRequest\022\014\n\004area\030\001 \001(\t\022\022\n\nisOccupie" +
      "d\030\002 \001(\010\" \n\rLightResponse\022\017\n\007message\030\001 \001(" +
      "\t2[\n\013SmartLights\022L\n\rControlLights\022\036.Smar" +
      "tOffices.OccupancyRequest\032\033.SmartOffices" +
      ".LightResponseB>\n#com.example.grpc.smart" +
      "offices.lightB\025SmartLightServiceImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOffices_OccupancyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOffices_OccupancyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_OccupancyRequest_descriptor,
        new java.lang.String[] { "Area", "IsOccupied", });
    internal_static_SmartOffices_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOffices_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_LightResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
