// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLights.proto

package com.example.grpc.smartoffices.light;

public final class SmartLightServiceImpl {
  private SmartLightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_LightResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SmartLights.proto\022\014SmartOffices\"\034\n\014Lig" +
      "htRequest\022\014\n\004area\030\001 \001(\t\" \n\rLightResponse" +
      "\022\017\n\007message\030\001 \001(\t2\370\002\n\013SmartLights\022A\n\006Tur" +
      "nOn\022\032.SmartOffices.LightRequest\032\033.SmartO" +
      "ffices.LightResponse\022B\n\007TurnOff\022\032.SmartO" +
      "ffices.LightRequest\032\033.SmartOffices.Light" +
      "Response\022G\n\014BrightnessUp\022\032.SmartOffices." +
      "LightRequest\032\033.SmartOffices.LightRespons" +
      "e\022I\n\016BrightnessDown\022\032.SmartOffices.Light" +
      "Request\032\033.SmartOffices.LightResponse\022N\n\021" +
      "StreamLightStatus\022\032.SmartOffices.LightRe" +
      "quest\032\033.SmartOffices.LightResponse0\001B>\n#" +
      "com.example.grpc.smartoffices.lightB\025Sma" +
      "rtLightServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOffices_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOffices_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_LightRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOffices_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_LightResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
