// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLight.proto

package com.project.grpc.smartoffices.light;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of people detected
   * </pre>
   *
   * <code>int32 numPeople = 1;</code>
   */
  int getNumPeople();
}
