// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartLight.proto

package com.project.grpc.smartoffices.light;

public interface LightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.LightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * True if light is on, False if off
   * </pre>
   *
   * <code>bool lightStatus = 1;</code>
   */
  boolean getLightStatus();

  /**
   * <code>int32 numPeople = 2;</code>
   */
  int getNumPeople();
}
