// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartWindow.proto

package com.project.grpc.smartoffices.window;

/**
 * Protobuf type {@code SmartOffices.WindowRequest}
 */
public  final class WindowRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SmartOffices.WindowRequest)
    WindowRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WindowRequest.newBuilder() to construct.
  private WindowRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WindowRequest() {
    windDirection_ = "";
    windSpeed_ = 0D;
    windTemperature_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WindowRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            windDirection_ = s;
            break;
          }
          case 17: {

            windSpeed_ = input.readDouble();
            break;
          }
          case 25: {

            windTemperature_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.project.grpc.smartoffices.window.SmartWindowServiceImpl.internal_static_SmartOffices_WindowRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.project.grpc.smartoffices.window.SmartWindowServiceImpl.internal_static_SmartOffices_WindowRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.project.grpc.smartoffices.window.WindowRequest.class, com.project.grpc.smartoffices.window.WindowRequest.Builder.class);
  }

  public static final int WINDDIRECTION_FIELD_NUMBER = 1;
  private volatile java.lang.Object windDirection_;
  /**
   * <code>string windDirection = 1;</code>
   */
  public java.lang.String getWindDirection() {
    java.lang.Object ref = windDirection_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      windDirection_ = s;
      return s;
    }
  }
  /**
   * <code>string windDirection = 1;</code>
   */
  public com.google.protobuf.ByteString
      getWindDirectionBytes() {
    java.lang.Object ref = windDirection_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      windDirection_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WINDSPEED_FIELD_NUMBER = 2;
  private double windSpeed_;
  /**
   * <code>double windSpeed = 2;</code>
   */
  public double getWindSpeed() {
    return windSpeed_;
  }

  public static final int WINDTEMPERATURE_FIELD_NUMBER = 3;
  private double windTemperature_;
  /**
   * <code>double windTemperature = 3;</code>
   */
  public double getWindTemperature() {
    return windTemperature_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getWindDirectionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, windDirection_);
    }
    if (windSpeed_ != 0D) {
      output.writeDouble(2, windSpeed_);
    }
    if (windTemperature_ != 0D) {
      output.writeDouble(3, windTemperature_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getWindDirectionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, windDirection_);
    }
    if (windSpeed_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, windSpeed_);
    }
    if (windTemperature_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, windTemperature_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.project.grpc.smartoffices.window.WindowRequest)) {
      return super.equals(obj);
    }
    com.project.grpc.smartoffices.window.WindowRequest other = (com.project.grpc.smartoffices.window.WindowRequest) obj;

    boolean result = true;
    result = result && getWindDirection()
        .equals(other.getWindDirection());
    result = result && (
        java.lang.Double.doubleToLongBits(getWindSpeed())
        == java.lang.Double.doubleToLongBits(
            other.getWindSpeed()));
    result = result && (
        java.lang.Double.doubleToLongBits(getWindTemperature())
        == java.lang.Double.doubleToLongBits(
            other.getWindTemperature()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WINDDIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getWindDirection().hashCode();
    hash = (37 * hash) + WINDSPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWindSpeed()));
    hash = (37 * hash) + WINDTEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWindTemperature()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.project.grpc.smartoffices.window.WindowRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.project.grpc.smartoffices.window.WindowRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SmartOffices.WindowRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SmartOffices.WindowRequest)
      com.project.grpc.smartoffices.window.WindowRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.grpc.smartoffices.window.SmartWindowServiceImpl.internal_static_SmartOffices_WindowRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.grpc.smartoffices.window.SmartWindowServiceImpl.internal_static_SmartOffices_WindowRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.grpc.smartoffices.window.WindowRequest.class, com.project.grpc.smartoffices.window.WindowRequest.Builder.class);
    }

    // Construct using com.project.grpc.smartoffices.window.WindowRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      windDirection_ = "";

      windSpeed_ = 0D;

      windTemperature_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.project.grpc.smartoffices.window.SmartWindowServiceImpl.internal_static_SmartOffices_WindowRequest_descriptor;
    }

    @java.lang.Override
    public com.project.grpc.smartoffices.window.WindowRequest getDefaultInstanceForType() {
      return com.project.grpc.smartoffices.window.WindowRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.project.grpc.smartoffices.window.WindowRequest build() {
      com.project.grpc.smartoffices.window.WindowRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.project.grpc.smartoffices.window.WindowRequest buildPartial() {
      com.project.grpc.smartoffices.window.WindowRequest result = new com.project.grpc.smartoffices.window.WindowRequest(this);
      result.windDirection_ = windDirection_;
      result.windSpeed_ = windSpeed_;
      result.windTemperature_ = windTemperature_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.project.grpc.smartoffices.window.WindowRequest) {
        return mergeFrom((com.project.grpc.smartoffices.window.WindowRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.project.grpc.smartoffices.window.WindowRequest other) {
      if (other == com.project.grpc.smartoffices.window.WindowRequest.getDefaultInstance()) return this;
      if (!other.getWindDirection().isEmpty()) {
        windDirection_ = other.windDirection_;
        onChanged();
      }
      if (other.getWindSpeed() != 0D) {
        setWindSpeed(other.getWindSpeed());
      }
      if (other.getWindTemperature() != 0D) {
        setWindTemperature(other.getWindTemperature());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.project.grpc.smartoffices.window.WindowRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.project.grpc.smartoffices.window.WindowRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object windDirection_ = "";
    /**
     * <code>string windDirection = 1;</code>
     */
    public java.lang.String getWindDirection() {
      java.lang.Object ref = windDirection_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        windDirection_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string windDirection = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWindDirectionBytes() {
      java.lang.Object ref = windDirection_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        windDirection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string windDirection = 1;</code>
     */
    public Builder setWindDirection(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      windDirection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string windDirection = 1;</code>
     */
    public Builder clearWindDirection() {
      
      windDirection_ = getDefaultInstance().getWindDirection();
      onChanged();
      return this;
    }
    /**
     * <code>string windDirection = 1;</code>
     */
    public Builder setWindDirectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      windDirection_ = value;
      onChanged();
      return this;
    }

    private double windSpeed_ ;
    /**
     * <code>double windSpeed = 2;</code>
     */
    public double getWindSpeed() {
      return windSpeed_;
    }
    /**
     * <code>double windSpeed = 2;</code>
     */
    public Builder setWindSpeed(double value) {
      
      windSpeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double windSpeed = 2;</code>
     */
    public Builder clearWindSpeed() {
      
      windSpeed_ = 0D;
      onChanged();
      return this;
    }

    private double windTemperature_ ;
    /**
     * <code>double windTemperature = 3;</code>
     */
    public double getWindTemperature() {
      return windTemperature_;
    }
    /**
     * <code>double windTemperature = 3;</code>
     */
    public Builder setWindTemperature(double value) {
      
      windTemperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double windTemperature = 3;</code>
     */
    public Builder clearWindTemperature() {
      
      windTemperature_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SmartOffices.WindowRequest)
  }

  // @@protoc_insertion_point(class_scope:SmartOffices.WindowRequest)
  private static final com.project.grpc.smartoffices.window.WindowRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.project.grpc.smartoffices.window.WindowRequest();
  }

  public static com.project.grpc.smartoffices.window.WindowRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WindowRequest>
      PARSER = new com.google.protobuf.AbstractParser<WindowRequest>() {
    @java.lang.Override
    public WindowRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WindowRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WindowRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WindowRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.project.grpc.smartoffices.window.WindowRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

