// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartWindow.proto

package com.example.grpc.smartoffices.window;

public interface WindowRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.WindowRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();
}
