// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartWindow.proto

package com.example.grpc.smartoffices.window;

public interface WindowResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.WindowResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Response message such as "Window opened" or "Tint adjusted"
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Response message such as "Window opened" or "Tint adjusted"
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
