// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartWindow.proto

package com.example.grpc.smartoffices.window;

public interface WindowResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.WindowResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * True if window is closed, False if open
   * </pre>
   *
   * <code>bool windowStatus = 1;</code>
   */
  boolean getWindowStatus();
}
