// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartWindow.proto

package com.example.grpc.smartoffices.window;

public interface WindowControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.WindowControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <pre>
   * Command such as "open", "close", "tint lighter", "tint darker"
   * </pre>
   *
   * <code>string command = 2;</code>
   */
  java.lang.String getCommand();
  /**
   * <pre>
   * Command such as "open", "close", "tint lighter", "tint darker"
   * </pre>
   *
   * <code>string command = 2;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();
}
