// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartlights.proto

package com.example.grpc.smartoffices;

public interface AdjustLightBrightnessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.AdjustLightBrightnessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>int32 brightness = 2;</code>
   */
  int getBrightness();
}
