// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartheating.proto

package com.example.grpc.smartoffices;

public interface AdjustHeatingTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.AdjustHeatingTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>float temperature = 2;</code>
   */
  float getTemperature();
}
