// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartwindow.proto

package com.example.grpc.smartoffices;

public interface AdjustWindowTintRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.AdjustWindowTintRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>int32 tint = 2;</code>
   */
  int getTint();
}
