// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartheating.proto

package com.example.grpc.smartoffices;

public interface GetHeatingStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.GetHeatingStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float temperature = 1;</code>
   */
  float getTemperature();
}
