// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartlights.proto

package com.example.grpc.smartoffices;

public interface GetLightStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.GetLightStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();
}
