// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartwindow.proto

package com.example.grpc.smartoffices;

/**
 * <pre>
 * GetWindowStatusResponse
 * </pre>
 *
 * Protobuf type {@code SmartOffices.GetWindowStatusResponse}
 */
public  final class GetWindowStatusResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SmartOffices.GetWindowStatusResponse)
    GetWindowStatusResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetWindowStatusResponse.newBuilder() to construct.
  private GetWindowStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetWindowStatusResponse() {
    isOpen_ = false;
    tint_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetWindowStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            isOpen_ = input.readBool();
            break;
          }
          case 16: {

            tint_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.grpc.smartoffices.SmartWindowServiceImpl.internal_static_SmartOffices_GetWindowStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.grpc.smartoffices.SmartWindowServiceImpl.internal_static_SmartOffices_GetWindowStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.grpc.smartoffices.GetWindowStatusResponse.class, com.example.grpc.smartoffices.GetWindowStatusResponse.Builder.class);
  }

  public static final int IS_OPEN_FIELD_NUMBER = 1;
  private boolean isOpen_;
  /**
   * <code>bool is_open = 1;</code>
   */
  public boolean getIsOpen() {
    return isOpen_;
  }

  public static final int TINT_FIELD_NUMBER = 2;
  private int tint_;
  /**
   * <code>int32 tint = 2;</code>
   */
  public int getTint() {
    return tint_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isOpen_ != false) {
      output.writeBool(1, isOpen_);
    }
    if (tint_ != 0) {
      output.writeInt32(2, tint_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isOpen_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isOpen_);
    }
    if (tint_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, tint_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.grpc.smartoffices.GetWindowStatusResponse)) {
      return super.equals(obj);
    }
    com.example.grpc.smartoffices.GetWindowStatusResponse other = (com.example.grpc.smartoffices.GetWindowStatusResponse) obj;

    boolean result = true;
    result = result && (getIsOpen()
        == other.getIsOpen());
    result = result && (getTint()
        == other.getTint());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_OPEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsOpen());
    hash = (37 * hash) + TINT_FIELD_NUMBER;
    hash = (53 * hash) + getTint();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.grpc.smartoffices.GetWindowStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.grpc.smartoffices.GetWindowStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * GetWindowStatusResponse
   * </pre>
   *
   * Protobuf type {@code SmartOffices.GetWindowStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SmartOffices.GetWindowStatusResponse)
      com.example.grpc.smartoffices.GetWindowStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.grpc.smartoffices.SmartWindowServiceImpl.internal_static_SmartOffices_GetWindowStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.grpc.smartoffices.SmartWindowServiceImpl.internal_static_SmartOffices_GetWindowStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.grpc.smartoffices.GetWindowStatusResponse.class, com.example.grpc.smartoffices.GetWindowStatusResponse.Builder.class);
    }

    // Construct using com.example.grpc.smartoffices.GetWindowStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isOpen_ = false;

      tint_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.grpc.smartoffices.SmartWindowServiceImpl.internal_static_SmartOffices_GetWindowStatusResponse_descriptor;
    }

    @java.lang.Override
    public com.example.grpc.smartoffices.GetWindowStatusResponse getDefaultInstanceForType() {
      return com.example.grpc.smartoffices.GetWindowStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.grpc.smartoffices.GetWindowStatusResponse build() {
      com.example.grpc.smartoffices.GetWindowStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.grpc.smartoffices.GetWindowStatusResponse buildPartial() {
      com.example.grpc.smartoffices.GetWindowStatusResponse result = new com.example.grpc.smartoffices.GetWindowStatusResponse(this);
      result.isOpen_ = isOpen_;
      result.tint_ = tint_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.grpc.smartoffices.GetWindowStatusResponse) {
        return mergeFrom((com.example.grpc.smartoffices.GetWindowStatusResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.grpc.smartoffices.GetWindowStatusResponse other) {
      if (other == com.example.grpc.smartoffices.GetWindowStatusResponse.getDefaultInstance()) return this;
      if (other.getIsOpen() != false) {
        setIsOpen(other.getIsOpen());
      }
      if (other.getTint() != 0) {
        setTint(other.getTint());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.grpc.smartoffices.GetWindowStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.grpc.smartoffices.GetWindowStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isOpen_ ;
    /**
     * <code>bool is_open = 1;</code>
     */
    public boolean getIsOpen() {
      return isOpen_;
    }
    /**
     * <code>bool is_open = 1;</code>
     */
    public Builder setIsOpen(boolean value) {
      
      isOpen_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_open = 1;</code>
     */
    public Builder clearIsOpen() {
      
      isOpen_ = false;
      onChanged();
      return this;
    }

    private int tint_ ;
    /**
     * <code>int32 tint = 2;</code>
     */
    public int getTint() {
      return tint_;
    }
    /**
     * <code>int32 tint = 2;</code>
     */
    public Builder setTint(int value) {
      
      tint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tint = 2;</code>
     */
    public Builder clearTint() {
      
      tint_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SmartOffices.GetWindowStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:SmartOffices.GetWindowStatusResponse)
  private static final com.example.grpc.smartoffices.GetWindowStatusResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.grpc.smartoffices.GetWindowStatusResponse();
  }

  public static com.example.grpc.smartoffices.GetWindowStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetWindowStatusResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetWindowStatusResponse>() {
    @java.lang.Override
    public GetWindowStatusResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetWindowStatusResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetWindowStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetWindowStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.grpc.smartoffices.GetWindowStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

