// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartwindow.proto

package com.example.grpc.smartoffices;

public interface GetWindowStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.GetWindowStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_open = 1;</code>
   */
  boolean getIsOpen();

  /**
   * <code>int32 tint = 2;</code>
   */
  int getTint();
}
