// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartheating.proto

package com.example.grpc.smartoffices;

public interface SetHeatingStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.SetHeatingStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string area = 1;</code>
   */
  java.lang.String getArea();
  /**
   * <code>string area = 1;</code>
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>bool status = 2;</code>
   */
  boolean getStatus();
}
