// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartlights.proto

package com.example.grpc.smartoffices;

public interface SetLightStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.SetLightStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
