// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartwindow.proto

package com.example.grpc.smartoffices;

public final class SmartWindowServiceImpl {
  private SmartWindowServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_OpenWindowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_OpenWindowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_OpenWindowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_OpenWindowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_CloseWindowRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_CloseWindowRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_CloseWindowResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_CloseWindowResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_GetWindowStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_GetWindowStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_GetWindowStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_GetWindowStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_SetWindowStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_SetWindowStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_SetWindowStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_SetWindowStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_AdjustWindowTintRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_AdjustWindowTintRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_AdjustWindowTintResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_AdjustWindowTintResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021smartwindow.proto\022\014SmartOffices\"!\n\021Ope" +
      "nWindowRequest\022\014\n\004area\030\001 \001(\t\"%\n\022OpenWind" +
      "owResponse\022\017\n\007success\030\001 \001(\010\"\"\n\022CloseWind" +
      "owRequest\022\014\n\004area\030\001 \001(\t\"&\n\023CloseWindowRe" +
      "sponse\022\017\n\007success\030\001 \001(\010\"&\n\026GetWindowStat" +
      "usRequest\022\014\n\004area\030\001 \001(\t\"8\n\027GetWindowStat" +
      "usResponse\022\017\n\007is_open\030\001 \001(\010\022\014\n\004tint\030\002 \001(" +
      "\005\"7\n\026SetWindowStatusRequest\022\014\n\004area\030\001 \001(" +
      "\t\022\017\n\007is_open\030\002 \001(\010\"*\n\027SetWindowStatusRes" +
      "ponse\022\017\n\007success\030\001 \001(\010\"5\n\027AdjustWindowTi" +
      "ntRequest\022\014\n\004area\030\001 \001(\t\022\014\n\004tint\030\002 \001(\005\"+\n" +
      "\030AdjustWindowTintResponse\022\017\n\007success\030\001 \001" +
      "(\0102\356\003\n\022SmartWindowService\022Q\n\nOpenWindow\022" +
      "\037.SmartOffices.OpenWindowRequest\032 .Smart" +
      "Offices.OpenWindowResponse\"\000\022T\n\013CloseWin" +
      "dow\022 .SmartOffices.CloseWindowRequest\032!." +
      "SmartOffices.CloseWindowResponse\"\000\022b\n\017Ge" +
      "tWindowStatus\022$.SmartOffices.GetWindowSt" +
      "atusRequest\032%.SmartOffices.GetWindowStat" +
      "usResponse\"\0000\001\022b\n\017SetWindowStatus\022$.Smar" +
      "tOffices.SetWindowStatusRequest\032%.SmartO" +
      "ffices.SetWindowStatusResponse\"\000(\001\022g\n\020Ad" +
      "justWindowTint\022%.SmartOffices.AdjustWind" +
      "owTintRequest\032&.SmartOffices.AdjustWindo" +
      "wTintResponse\"\000(\0010\001B9\n\035com.example.grpc." +
      "smartofficesB\026SmartWindowServiceImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOffices_OpenWindowRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOffices_OpenWindowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_OpenWindowRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_OpenWindowResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOffices_OpenWindowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_OpenWindowResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SmartOffices_CloseWindowRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartOffices_CloseWindowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_CloseWindowRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_CloseWindowResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartOffices_CloseWindowResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_CloseWindowResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SmartOffices_GetWindowStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartOffices_GetWindowStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_GetWindowStatusRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_GetWindowStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SmartOffices_GetWindowStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_GetWindowStatusResponse_descriptor,
        new java.lang.String[] { "IsOpen", "Tint", });
    internal_static_SmartOffices_SetWindowStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SmartOffices_SetWindowStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_SetWindowStatusRequest_descriptor,
        new java.lang.String[] { "Area", "IsOpen", });
    internal_static_SmartOffices_SetWindowStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SmartOffices_SetWindowStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_SetWindowStatusResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SmartOffices_AdjustWindowTintRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_SmartOffices_AdjustWindowTintRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_AdjustWindowTintRequest_descriptor,
        new java.lang.String[] { "Area", "Tint", });
    internal_static_SmartOffices_AdjustWindowTintResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_SmartOffices_AdjustWindowTintResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_AdjustWindowTintResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
