// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartheating.proto

package com.example.grpc.smartoffices;

public final class SmartHeatingServiceImpl {
  private SmartHeatingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TurnOnHeatingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TurnOnHeatingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TurnOnHeatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TurnOnHeatingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TurnOffHeatingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TurnOffHeatingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TurnOffHeatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TurnOffHeatingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_GetHeatingStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_GetHeatingStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_GetHeatingStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_GetHeatingStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_SetHeatingStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_SetHeatingStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_SetHeatingStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_SetHeatingStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_AdjustHeatingTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_AdjustHeatingTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_AdjustHeatingTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_AdjustHeatingTemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022smartheating.proto\022\014SmartOffices\"$\n\024Tu" +
      "rnOnHeatingRequest\022\014\n\004area\030\001 \001(\t\"(\n\025Turn" +
      "OnHeatingResponse\022\017\n\007success\030\001 \001(\010\"%\n\025Tu" +
      "rnOffHeatingRequest\022\014\n\004area\030\001 \001(\t\")\n\026Tur" +
      "nOffHeatingResponse\022\017\n\007success\030\001 \001(\010\"\'\n\027" +
      "GetHeatingStatusRequest\022\014\n\004area\030\001 \001(\t\"/\n" +
      "\030GetHeatingStatusResponse\022\023\n\013temperature" +
      "\030\001 \001(\002\"7\n\027SetHeatingStatusRequest\022\014\n\004are" +
      "a\030\001 \001(\t\022\016\n\006status\030\002 \001(\010\"+\n\030SetHeatingSta" +
      "tusResponse\022\017\n\007success\030\001 \001(\010\"D\n\037AdjustHe" +
      "atingTemperatureRequest\022\014\n\004area\030\001 \001(\t\022\023\n" +
      "\013temperature\030\002 \001(\002\"3\n AdjustHeatingTempe" +
      "ratureResponse\022\017\n\007success\030\001 \001(\0102\237\004\n\023Smar" +
      "tHeatingService\022Z\n\rTurnOnHeating\022\".Smart" +
      "Offices.TurnOnHeatingRequest\032#.SmartOffi" +
      "ces.TurnOnHeatingResponse\"\000\022]\n\016TurnOffHe" +
      "ating\022#.SmartOffices.TurnOffHeatingReque" +
      "st\032$.SmartOffices.TurnOffHeatingResponse" +
      "\"\000\022e\n\020GetHeatingStatus\022%.SmartOffices.Ge" +
      "tHeatingStatusRequest\032&.SmartOffices.Get" +
      "HeatingStatusResponse\"\0000\001\022e\n\020SetHeatingS" +
      "tatus\022%.SmartOffices.SetHeatingStatusReq" +
      "uest\032&.SmartOffices.SetHeatingStatusResp" +
      "onse\"\000(\001\022\177\n\030AdjustHeatingTemperature\022-.S" +
      "martOffices.AdjustHeatingTemperatureRequ" +
      "est\032..SmartOffices.AdjustHeatingTemperat" +
      "ureResponse\"\000(\0010\001B:\n\035com.example.grpc.sm" +
      "artofficesB\027SmartHeatingServiceImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOffices_TurnOnHeatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOffices_TurnOnHeatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TurnOnHeatingRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_TurnOnHeatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOffices_TurnOnHeatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TurnOnHeatingResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SmartOffices_TurnOffHeatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartOffices_TurnOffHeatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TurnOffHeatingRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_TurnOffHeatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartOffices_TurnOffHeatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TurnOffHeatingResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SmartOffices_GetHeatingStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartOffices_GetHeatingStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_GetHeatingStatusRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_GetHeatingStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SmartOffices_GetHeatingStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_GetHeatingStatusResponse_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_SmartOffices_SetHeatingStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SmartOffices_SetHeatingStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_SetHeatingStatusRequest_descriptor,
        new java.lang.String[] { "Area", "Status", });
    internal_static_SmartOffices_SetHeatingStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SmartOffices_SetHeatingStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_SetHeatingStatusResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SmartOffices_AdjustHeatingTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_SmartOffices_AdjustHeatingTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_AdjustHeatingTemperatureRequest_descriptor,
        new java.lang.String[] { "Area", "Temperature", });
    internal_static_SmartOffices_AdjustHeatingTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_SmartOffices_AdjustHeatingTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_AdjustHeatingTemperatureResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
