// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartlights.proto

package com.example.grpc.smartoffices;

public final class SmartLightServiceImpl {
  private SmartLightServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TurnOnLightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TurnOnLightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TurnOnLightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TurnOnLightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TurnOffLightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TurnOffLightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TurnOffLightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TurnOffLightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_GetLightStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_GetLightStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_GetLightStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_GetLightStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_SetLightStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_SetLightStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_SetLightStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_SetLightStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_AdjustLightBrightnessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_AdjustLightBrightnessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_AdjustLightBrightnessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_AdjustLightBrightnessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021smartlights.proto\022\014SmartOffices\"\"\n\022Tur" +
      "nOnLightRequest\022\014\n\004area\030\001 \001(\t\"&\n\023TurnOnL" +
      "ightResponse\022\017\n\007success\030\001 \001(\010\"#\n\023TurnOff" +
      "LightRequest\022\014\n\004area\030\001 \001(\t\"\'\n\024TurnOffLig" +
      "htResponse\022\017\n\007success\030\001 \001(\010\"%\n\025GetLightS" +
      "tatusRequest\022\014\n\004area\030\001 \001(\t\"(\n\026GetLightSt" +
      "atusResponse\022\016\n\006status\030\001 \001(\010\"5\n\025SetLight" +
      "StatusRequest\022\014\n\004area\030\001 \001(\t\022\016\n\006status\030\002 " +
      "\001(\010\")\n\026SetLightStatusResponse\022\017\n\007success" +
      "\030\001 \001(\010\"@\n\034AdjustLightBrightnessRequest\022\014" +
      "\n\004area\030\001 \001(\t\022\022\n\nbrightness\030\002 \001(\005\"0\n\035Adju" +
      "stLightBrightnessResponse\022\017\n\007success\030\001 \001" +
      "(\0102\374\003\n\021SmartLightService\022T\n\013TurnOnLight\022" +
      " .SmartOffices.TurnOnLightRequest\032!.Smar" +
      "tOffices.TurnOnLightResponse\"\000\022W\n\014TurnOf" +
      "fLight\022!.SmartOffices.TurnOffLightReques" +
      "t\032\".SmartOffices.TurnOffLightResponse\"\000\022" +
      "_\n\016GetLightStatus\022#.SmartOffices.GetLigh" +
      "tStatusRequest\032$.SmartOffices.GetLightSt" +
      "atusResponse\"\0000\001\022_\n\016SetLightStatus\022#.Sma" +
      "rtOffices.SetLightStatusRequest\032$.SmartO" +
      "ffices.SetLightStatusResponse\"\000(\001\022v\n\025Adj" +
      "ustLightBrightness\022*.SmartOffices.Adjust" +
      "LightBrightnessRequest\032+.SmartOffices.Ad" +
      "justLightBrightnessResponse\"\000(\0010\001B8\n\035com" +
      ".example.grpc.smartofficesB\025SmartLightSe" +
      "rviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOffices_TurnOnLightRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOffices_TurnOnLightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TurnOnLightRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_TurnOnLightResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOffices_TurnOnLightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TurnOnLightResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SmartOffices_TurnOffLightRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartOffices_TurnOffLightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TurnOffLightRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_TurnOffLightResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartOffices_TurnOffLightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TurnOffLightResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SmartOffices_GetLightStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartOffices_GetLightStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_GetLightStatusRequest_descriptor,
        new java.lang.String[] { "Area", });
    internal_static_SmartOffices_GetLightStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_SmartOffices_GetLightStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_GetLightStatusResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_SmartOffices_SetLightStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SmartOffices_SetLightStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_SetLightStatusRequest_descriptor,
        new java.lang.String[] { "Area", "Status", });
    internal_static_SmartOffices_SetLightStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_SmartOffices_SetLightStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_SetLightStatusResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_SmartOffices_AdjustLightBrightnessRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_SmartOffices_AdjustLightBrightnessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_AdjustLightBrightnessRequest_descriptor,
        new java.lang.String[] { "Area", "Brightness", });
    internal_static_SmartOffices_AdjustLightBrightnessResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_SmartOffices_AdjustLightBrightnessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_AdjustLightBrightnessResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
