// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartheating.proto

package com.example.grpc.smartoffices;

public interface TurnOnHeatingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.TurnOnHeatingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
