// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.project.grpc.smartoffices.heating;

public interface HeatingAdjustmentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.HeatingAdjustmentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * True if heating is on, False if off
   * </pre>
   *
   * <code>bool heatingStatus = 1;</code>
   */
  boolean getHeatingStatus();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
