// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.project.grpc.smartoffices.heating;

public final class SmartHeatingServiceImpl {
  private SmartHeatingServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_HeatingAdjustmentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_HeatingAdjustmentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_HeatingAdjustmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_HeatingAdjustmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TemperatureStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TemperatureStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartOffices_TemperatureStreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartOffices_TemperatureStreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SmartHeating.proto\022\014SmartOffices\"W\n\030He" +
      "atingAdjustmentRequest\022\023\n\013temperature\030\001 " +
      "\001(\001\022\020\n\010humidity\030\002 \001(\001\022\024\n\014airPollution\030\003 " +
      "\001(\001\"C\n\031HeatingAdjustmentResponse\022\025\n\rheat" +
      "ingStatus\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\",\n\030Temp" +
      "eratureStreamRequest\022\020\n\010clientId\030\001 \001(\t\"_" +
      "\n\031TemperatureStreamResponse\022\032\n\022currentTe" +
      "mperature\030\001 \001(\001\022\025\n\rheatingStatus\030\002 \001(\010\022\017" +
      "\n\007message\030\003 \001(\t2\337\001\n\014SmartHeating\022`\n\rAdju" +
      "stHeating\022&.SmartOffices.HeatingAdjustme" +
      "ntRequest\032\'.SmartOffices.HeatingAdjustme" +
      "ntResponse\022m\n\030StreamTemperatureUpdates\022&" +
      ".SmartOffices.TemperatureStreamRequest\032\'" +
      ".SmartOffices.TemperatureStreamResponse0" +
      "\001BB\n%com.project.grpc.smartoffices.heati" +
      "ngB\027SmartHeatingServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartOffices_HeatingAdjustmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartOffices_HeatingAdjustmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_HeatingAdjustmentRequest_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "AirPollution", });
    internal_static_SmartOffices_HeatingAdjustmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartOffices_HeatingAdjustmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_HeatingAdjustmentResponse_descriptor,
        new java.lang.String[] { "HeatingStatus", "Message", });
    internal_static_SmartOffices_TemperatureStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartOffices_TemperatureStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TemperatureStreamRequest_descriptor,
        new java.lang.String[] { "ClientId", });
    internal_static_SmartOffices_TemperatureStreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartOffices_TemperatureStreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartOffices_TemperatureStreamResponse_descriptor,
        new java.lang.String[] { "CurrentTemperature", "HeatingStatus", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
