// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.project.grpc.smartoffices.heating;

public interface TemperatureStreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.TemperatureStreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Current temperature
   * </pre>
   *
   * <code>double currentTemperature = 1;</code>
   */
  double getCurrentTemperature();

  /**
   * <pre>
   * True if heating is on, False if off
   * </pre>
   *
   * <code>bool heatingStatus = 2;</code>
   */
  boolean getHeatingStatus();
}
