// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHeating.proto

package com.project.grpc.smartoffices.heating;

public interface TemperatureStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartOffices.TemperatureStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifier for the client requesting the data
   * </pre>
   *
   * <code>string clientId = 1;</code>
   */
  java.lang.String getClientId();
  /**
   * <pre>
   * Identifier for the client requesting the data
   * </pre>
   *
   * <code>string clientId = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
